apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: etl-enriched-users-analysis-iceberg
  namespace: processing
spec:
  type: Python
  mode: cluster
  image: "owshq/etl-enriched-users-analysis-iceberg:3.2.1"
  imagePullPolicy: Always
  mainApplicationFile: "local:///app/etl-enriched-users-analysis.py"
  sparkVersion: "3.1.1"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  hadoopConf:
    "fs.s3a.endpoint": "http://minio-ip"
  sparkConf:
    "spark.sql.catalog.owshq.s3.endpoint": "http://minio-ip"
    "spark.sql.catalog.owshq.uri": "thrift://hive-metastore-ip:9083"
  driver:
    # cores: 1
    coreRequest: 250m
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.1
    serviceAccount: default
  executor:
    # cores: 1
    coreRequest: 250m
    instances: 3
    memory: "512m"
    labels:
      version: 3.1.1
